#!/usr/bin/env bash
set -euxo pipefail

DRY_RUN=${1:-}

rsync -av $DRY_RUN init.vim $HOME/.config/nvim/init.vim
rsync -av $DRY_RUN ginit.vim $HOME/.config/nvim/ginit.vim
rsync -av $DRY_RUN --exclude='*.original' colors/ $HOME/.config/nvim/colors/
rsync -av $DRY_RUN --exclude='*.original' syntax/ $HOME/.config/nvim/syntax/
rsync -av $DRY_RUN --exclude='*.original' indent/ $HOME/.config/nvim/indent/
rsync -av $DRY_RUN --exclude=.git bundle/ $HOME/.config/nvim/bundle/

